### PR TITLE
Function new line fix

### PR DESCRIPTION
**Pull request by nathangur**

### CODE REVIEW

**Comment by nathangur** [comment]
Fixed < and > showing up as &lt;

**Comment by nathangur** [comment]
:/

**Comment by Thomasims** [comment]
So the initial purpose of this PR was replaced by the HTML entities fix then? I wasn't really in favor of the initial change anyway but now I'll just write something to handle some of the other HTML entities since the code already deals with `&nbsp;` in tables.

**Comment by nathangur** [comment]
Yeah that was the purpose to fix 2 characters and new lines

**Pull request merged**
